sonar.projectKey=access-governance-go-sdk
sonar.projectName=@collibra/access-governance-go-sdk
sonar.issuesReport.html.enable=true
sonar.report.export.path=sonar-report.json
sonar.sources=.
sonar.test.inclusions=**/*_test.go

#sonar.analysis.mode=preview
sonar.issuesReport.html.enable=true
sonar.go.coverage.reportPaths=coverage.txt