sonar.projectKey=data-access-go-sdk
sonar.projectName=@collibra/data-access-go-sdk
sonar.issuesReport.html.enable=true
sonar.report.export.path=sonar-report.json
sonar.sources=.
sonar.test.inclusions=**/*_test.go
onar.exclusions=**/*_test.go,**/vendor/**,types/generated.go,internal/schema/generated.go

sonar.junit.reportPaths=.tests/test-results.xml
sonar.go.tests.reportPaths=.tests/test-results.json
sonar.go.coverage.reportPaths=.tests/coverage.out
sonar.go.golangci-lint.reportPaths=.tests/golangci-lint.xml