name: Validate Collibra Data Access SDK
run-name: Validation of Collibra Data Access SDK
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
#  generate:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v5
#        with:
#          go-version-file: 'go.mod'
#          cache: true
#      - run: go generate ./...
#      - name: git diff
#        run: |
#          git diff --compact-summary --exit-code || \
#            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
  build:
    runs-on:
      - runs-on
      - runner=md
      - env=production-eu
      - run-id=${{ github.run_id }}
      - tag=validation-build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Mod Tidy
        run: go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.8.0

      - name: Build
        run: go build ./...

      - name: Test
        run: make test-coverage
        env:
          COLLIBRA_URL: ${{ secrets.COLLIBRA_URL }}
          COLLIBRA_USER: ${{ secrets.COLLIBRA_USER }}
          COLLIBRA_PASSWORD: ${{ secrets.COLLIBRA_PASSWORD }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PUBLIC_API_KEY }}
          SONAR_HOST_URL: https://sonarqube.collibra.dev
        with:
          args: >
            -Dsonar.pullrequest.github.repository=collibra/data-access-go-sdk

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 10
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PUBLIC_API_KEY }}
          SONAR_HOST_URL: https://sonarqube.collibra.dev

      - name: FOSSA Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_PUBLIC_API_KEY }}